# Generated by Django 6.0.4 on 2026-04-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_name',
            field=models.CharField(default='Unknwon', max_length=100),
        ),
    ]
