# Generated by Django 6.0.4 on 2026-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_profile_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sample_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
